import images from './index.js';

const { TallyMax, wishList, weatherView, onBase, readTheory, woodlandConsulting, keep, shopShop } = images

const project_info = [
    {
        key: 1,
        src: woodlandConsulting,
        name: 'woodlandConsulting',
        width: 2,
        alt: 'Woodland Consulting application screenshot',
        title: 'Woodland Consulting LLC',
        description: 'Group Project: MERN wesite for a small lighting design and engineering firm',
        repository: 'https://github.com/SMKrizan/WoodlandConsultingLLC',
        deployment: 'https://woodland-consulting.herokuapp.com/',
    },
    {
        key: 2,
        src: TallyMax,
        name: 'TallyMax',
        width: 1,
        alt: 'TallyMax application screenshot',
        title: "TallyMax",
        description: 'Group Project: learn new words with this word-generator including definitions, audio and images',
        respository: 'https://github.com/jgrossh2/word-generator',
        deployment: 'https://jgrossh2.github.io/word-generator/',
    },
    {        
        key: 3,
        src: wishList,
        name: 'wishList',
        width: 1,
        alt: '12 Wishes application screenshot',
        title: "12 Wishes",
        description: 'Group Project: holiday wish lists',
        repository: 'https://github.com/chriswein12/wish-list',
        deployment: 'https://twelve-wishes.herokuapp.com/',
    },
    {
        key: 4,
        src: keep,
        name: 'keep',
        width: 1,
        alt: 'keep budget-tracker application screenshot',
        title: '.keep',
        description: 'simple budget-tracker and Progressive Web App (PWA) using IndexedDB to facilitate a consistent user experience even with spotty internet reception',
        repository: 'https://github.com/SMKrizan/keep',
        deployment: 'https://keep-budget-app.herokuapp.com/',
    },
    {
        key: 5,
        src: onBase,
        name: 'onBase',
        width: 1,
        alt: 'onBase application screenshot',
        title: "onBase",
        desription: 'A Content Management System (CMS) for tracking employee data that runs from the command-line',
        repository: 'https://github.com/SMKrizan/onBase',
        deployment: '',
    },
    {
        key: 6,
        src: readTheory,
        name: 'readTheory',
        width: 1,
        alt: 'readTheory application screenshot',
        title: "readTheory",
        description: 'a note-taking application',
        repository: 'https://github.com/SMKrizan/readTheory',
        deployment: 'https://readtheory.herokuapp.com/',
    },
    {
        key: 7,
        src: weatherView,
        name: 'weatherView',
        width: 2,
        alt: 'weatherView application screenshot',
        title: "Weather View",
        description: 'an application for accessing current & forecasted weather using a 3rd-party API',
        repository: 'https://github.com/smkrizan/WeatherView/',
        deployment: 'https://smkrizan.github.io/WeatherView/',
    },
    {
        key: 8,
        src: shopShop,
        name: 'shopShop',
        width: 1,
        alt: 'shopShop application screenshot',
        title: "Shop-Shop",
        description: 'an e-commerce website using Redux and Stripe payment platform',
        repository: 'https://github.com/SMKrizan/shopShop-Redux',
        deployment: 'https://shopshop-redux.herokuapp.com/',
}
]

export default { project_info };
