import projects from './index.js';

const { TallyMax, wishList, weatherView, onBase, readTheory, woodlandConsulting, keep, shopShop } = projects

const project_info = [
    {
        src: woodlandConsulting,
        width: 2,
        height: 1,
        alt: 'Woodland Consulting application screenshot',
        title: 'Woodland Consulting LLC',
        description: 'Group Project: MERN wesite for a small lighting design and engineering firm',
        languages: 'Javascript',
        repository: 'https://github.com/SMKrizan/WoodlandConsultingLLC',
        deployment: 'https://woodland-consulting.herokuapp.com/',
    },
    {
        src: TallyMax,
        width: 1,
        height: 1,
        alt: 'TallyMax application screenshot',
        title: "TallyMax",
        description: 'Group Project: learn new words with this word-generator including definitions, audio and images',
        languages: 'Javascript',
        respository: 'https://github.com/jgrossh2/word-generator',
        deployment: 'https://jgrossh2.github.io/word-generator/',
    },
    {
        src: wishList,
        width: 1,
        height: 1,
        alt: '12 Wishes application screenshot',
        title: "12Wishes",
        description: 'Group Project: holiday wish lists',
        languages: 'Javascript, Handlebars, SCSS',
        repository: 'https://github.com/chriswein12/wish-list',
        deployment: 'https://twelve-wishes.herokuapp.com/',
    },
    {
        src: keep,
        width: 1,
        height: 1,
        alt: 'keep budget-tracker application screenshot',
        title: 'keep',
        description: 'simple budget-tracker and Progressive Web App (PWA) using IndexedDB to facilitate a consistent user experience even with spotty internet reception',
        languages: 'Javascript',
        repository: 'https://github.com/SMKrizan/keep',
        deployment: 'https://keep-budget-app.herokuapp.com/',
    },
    {
        src: onBase,
        width: 1,
        height: 1,
        alt: 'onBase application screenshot',
        description: ,
        title: "onBase",
        languages: 'A Content Management System (CMS) for tracking employee data that runs from the command-line',
        repository: 'https://github.com/SMKrizan/onBase',
        deployment: '',
    },
    {
        src: readTheory,
        width: 1,
        height: 1,
        alt: 'readTheory application screenshot',
        title: '"readTheory" note taking app ({languages: Javascript, HTML, CSS}, {repo: https://github.com/SMKrizan/readTheory}, {link: https://readtheory.herokuapp.com/})',
        description: ,
        languages: ,
        repository: ,
        deployment: ,
    },
    {
        src: weatherView,
        width: 2,
        height: 1,
        alt: 'weatherView application screenshot',
        title: '"WeatherView" access current & forecasted weather using 3rd party API ({languages: Javascript, HTML, CSS}, {repo: https://github.com/smkrizan/WeatherView/}, {link: https://smkrizan.github.io/WeatherView/})',
        description: ,
        languages: ,
        repository: ,
        deployment: ,
    },
    {
        src: shopShop,
        width: 1,
        height: 1,
        alt: 'shopShop application screenshot',
        title: '"shopShop" e-commerce website using Redux and Stripe payment platform ({languages: Javascript}, {repo: https://github.com/SMKrizan/shopShop-Redux}, {link:  https://shopshop-redux.herokuapp.com/})',
        description: ,
        languages: ,
        repository: ,
        deployment: ,
}
]

export default {photos};
